name: ESLint

on: [push, pull_request]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install ESLint
        run: npm install -g eslint


      - name: Install ESLint plugin
        run: npm install @typescript-eslint/eslint-plugin^5.53.0 --save-dev

      - name: Run ESLint
        run: npm run lint
